[workspace]
authors = ["Jan Kotanski <jankotan@gmail.com>"]
channels = ["conda-forge"]
name = "nxstools"
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "osx-64", "win-64"]
version = "1.0.1"

[tasks]

[dependencies]
python = "==3.13"
# conda-smithy = ">=3.56.3,<4"
# rattler-build = ">=0.60.0,<0.61"
# ipython = ">=9.11.0,<10"
