.TH nxscomp_selector 1 "2014-08-09" nxscomp_selector
.SH NAME
.B nxscomp_selector
\- Component selector GUI for Sardana Nexus Recorder

.SH SYNOPSIS
.B  nxscomp_selector
[
.I OPTIONS
] [
.I <arguments>
]

.SH DESCRIPTION
.B nxscomp_selector
is a GUI configuration tool dedicated to select components 
as well as datasources which constitute the XML configuration strings of 
Nexus Data Writer via Sardana NeXus Recorder.


.SH OPTIONS
.\".IP "--version"
.\"show program's version number and exit
.IP "--help, -h"
show a help message and exit
.IP "--server, -s"
selector server
.IP "--style, -t"
QT style
.IP "--stylesheet, -y"
QT style sheet
        

.SH SEE ALSO
https://github.com/jkotan/nexdatas/

.SH COPYRIGHT
Copyrights (c) 2014, GNU GPL v2, DESY, Jan Kotanski

.SH BUGS
Please report bugs on the project's mailing list:
mailto://jankotan@gmail.com

.SH AUTHORS
Jan Kotanski <jankotan@gmail.com>,

